### ISSUE TITLE
May need `bar.finish()` when finish

### ISSUE THREAD

**Issue by district10** [aminnj/cpptqdm#4]
You may need to mention it in the README. Without `bar.finish()`, the progress bar just disappears in the end. You end up without knowing the speed of these iterations. (I found tqdm useful as a benchmark)

**Comment by aminnj** [comment]
good point. thanks! I put it in the readme: https://github.com/aminnj/cpptqdm/commit/04c733fd38cdc1763d7bc19f8ff3a8fb6e95e2e9
